/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline;

/**
 *
 * @author Dell
 */
import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.event.*;
import java.util.*;

public class updateFlight extends javax.swing.JFrame {

    /**
     * Creates new form updateFlight
     */
    Flight flightObj;
    FlightRecord flightRecord;
    String flightNumber;
    public updateFlight() {
        this.flightRecord=new FlightRecord();
        initComponents();
    }

    public updateFlight(Flight obj) {
        initComponents();
        this.flightRecord=new FlightRecord();
        flightNumber=obj.flightNo;
        this.flightObj = new Flight(obj.flightNo, obj.airline, obj.origin, obj.destination, obj.date, obj.time);
        flightNoField.setText(obj.flightNo);
        airlineField.setText(obj.airline);
        originField.setText(obj.origin);
        destinationField.setText(obj.destination);
        String day = obj.date.substring(0, 2);
        String month = obj.date.substring(3, obj.date.indexOf(","));
        String year = obj.date.substring(obj.date.indexOf(",") + 1);
        
        for (int i = 0; i < 30; i++) {
            if (dayBox.getItemAt(i).toString().contains(day)) {
                dayBox.setSelectedIndex(i);
            }
        }
        monthBox.setSelectedItem(month);
        yearBox.setSelectedItem(year);

        
        String hour = obj.time.substring(0, 2);
        String minute = obj.time.substring(3, 5);
        String amPm = obj.time.substring(6);
        hourBox.setSelectedItem(hour);
        minuteBox.setSelectedItem(minute);
        amPmBox.setSelectedItem(amPm);

        System.out.println(day);
        System.out.println(month);
        System.out.println(year);
        System.out.println(hour);
        System.out.println(minute);
        System.out.println(amPm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        saveUpdateButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        flightNoField = new javax.swing.JTextField();
        airlineField = new javax.swing.JTextField();
        originField = new javax.swing.JTextField();
        destinationField = new javax.swing.JTextField();
        dayBox = new javax.swing.JComboBox<>();
        monthBox = new javax.swing.JComboBox<>();
        yearBox = new javax.swing.JComboBox<>();
        hourBox = new javax.swing.JComboBox<>();
        minuteBox = new javax.swing.JComboBox<>();
        amPmBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("Update Flight");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel2.setText("Flight No:");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel3.setText("Airline:");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel4.setText("Origin:");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel5.setText("Destination:");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel6.setText("Date:");

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel7.setText("Time:");

        saveUpdateButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        saveUpdateButton.setText("SAVE");
        saveUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUpdateButtonActionPerformed(evt);
            }
        });

        goBackButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        goBackButton.setText("GO BACK");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        flightNoField.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N

        airlineField.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N

        originField.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N

        destinationField.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N

        dayBox.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        dayBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        monthBox.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        monthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        yearBox.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        yearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016","2017","2018","2019" }));

        hourBox.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        hourBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01","02","03","04","05","06","07","08","09","10","11","12"  }));

        minuteBox.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        minuteBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00","01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59"}));

        amPmBox.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        amPmBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM","PM" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(goBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(saveUpdateButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dayBox, 0, 38, Short.MAX_VALUE)
                            .addComponent(hourBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(monthBox, 0, 111, Short.MAX_VALUE)
                            .addComponent(minuteBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(yearBox, 0, 57, Short.MAX_VALUE)
                            .addComponent(amPmBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(flightNoField)
                    .addComponent(destinationField)
                    .addComponent(airlineField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(originField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(flightNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(airlineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(originField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(destinationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(hourBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuteBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amPmBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goBackButton)
                    .addComponent(saveUpdateButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUpdateButtonActionPerformed
        
        //update button
        
        String date=dayBox.getSelectedItem().toString()+" "+monthBox.getSelectedItem().toString()+","+yearBox.getSelectedItem().toString();
        String time=hourBox.getSelectedItem().toString()+":"+minuteBox.getSelectedItem().toString()+" "+amPmBox.getSelectedItem().toString();

       // flightObj=new Flight(jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),date,time);
        if (flightRecord.update(flightNumber,flightNoField.getText(),airlineField.getText(),originField.getText(),destinationField.getText(),date,time)){
            JOptionPane.showMessageDialog(null,flightNoField.getText()+  " updated!");
            ManageFlights manageFlights=new ManageFlights();
            manageFlights.setVisible(true);
            this.hide();
           
        }
        else{
            JOptionPane.showMessageDialog(null,"Invalid input! Only UNIQUE entries are allowed in Flight Number Field!");
            ManageFlights manageFlights=new ManageFlights();
            manageFlights.setVisible(true);
            this.hide();
        }
    }//GEN-LAST:event_saveUpdateButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        //code for GO BACK Button
        ManageFlights manageFlights=new ManageFlights();
        manageFlights.setVisible(true);
        this.hide();
    }//GEN-LAST:event_goBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlineField;
    private javax.swing.JComboBox<String> amPmBox;
    private javax.swing.JComboBox<String> dayBox;
    private javax.swing.JTextField destinationField;
    private javax.swing.JTextField flightNoField;
    private javax.swing.JButton goBackButton;
    private javax.swing.JComboBox<String> hourBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> minuteBox;
    private javax.swing.JComboBox<String> monthBox;
    private javax.swing.JTextField originField;
    private javax.swing.JButton saveUpdateButton;
    private javax.swing.JComboBox<String> yearBox;
    // End of variables declaration//GEN-END:variables
}
